export default [
  {
    name: 'Moscow',
    country: 'Russia',
    region: 'Moscow City',
    lat: '55.752',
    lon: '37.616',
    timezone_id: 'Europe/Moscow',
    utc_offset: '3.0',
  },
  {
    name: 'Moscow',
    country: 'United States of America',
    region: 'Idaho',
    lat: '46.733',
    lon: '-116.999',
    timezone_id: 'America/Los_Angeles',
    utc_offset: '-8.0',
  },
  {
    name: 'Budapest',
    country: 'Hungary',
    region: 'Budapest',
    lat: '47.500',
    lon: '19.083',
    timezone_id: 'Europe/Budapest',
    localtime: '2019-12-16 10:06',
    localtime_epoch: 1576490760,
    utc_offset: '1.0',
  },
];
